### ISSUE TITLE
song browser not in new mod update rly need it help

### ISSUE THREAD

**Issue by nxnee** [Umbranoxio/BeatSaberModInstaller#104] opened 2019-03-15 23:56 UTC

**Comment by stevemazg** [comment] 2019-03-16 00:35
Just click on Extras (250 songs). Still lots missing though, update required asap :(

**Comment by phiresky** [comment] 2019-03-16 14:29
duplicate of #101. you should learn how github works before spamming people with emails.

**Comment by notyoyoma** [comment] 2019-03-20 14:36
Hey @nxnee, If you're still dealing with this issue, @megalon explained the current state of the project [here](https://github.com/Umbranoxio/BeatSaberModInstaller/issues/103#issuecomment-474804108).

TLDR: [This new repo](https://github.com/lolPants/modsaber-installer/) should work, and get you playing again

**Closed as completed** 2019-04-08 09:39 UTC
